### ISSUE TITLE
Twitter auto dark mode causes three-dot-menu to not function anymore (+ Safari window history back bug)

### ISSUE THREAD

**Issue by SebastianRasch** [Andrew-J-Larson/Custom-JS#12]
Hi, some changes on the website must've lead to your script causing the kebab menu on any post ("More") to not work anymore when it's active. Would you look into it?

<img width="650" alt="Screenshot 2024-02-11 at 16 20 42" src="https://github.com/Andrew-J-Larson/Custom-JS/assets/22617697/d94903d4-516a-4ca8-ae7f-704548e32328">

**Comment by SebastianRasch** [comment]
It's not auto-switching anymore either I just realised. Must've change the menu structure again.

**Comment by Andrew-J-Larson** [comment]
@SebastianRasch got around to it, and fixed it, should be working now for the "Dim" and "Lights Out" variants.

**Comment by SebastianRasch** [comment]
Awesome, thank you so much! Works like a charm!

For what it's worth, I believe you don't have to be "the Elon supporting type" to appreciate Twitter. It's become a lot better recently and they're updating it so much more than before Elon took over, it's seen tremendous improvements and I think it's just the beginning, so much more to come. I think Twitter more promising today than it's ever been.
It's not about a person – there's many enterprises whose leadership and their decisions I don't support at all. I don't have to identify with them nor with their products to enjoy the products anyway or to find them at least helpful.

Not saying Twitter is perfect, just want to encourage to give it another chance, that's all 😉 You can train your personal algorithm so you only get content you like. The longer you use it and depending on who you follow and interact with the more interesting and engaging your feed becomes. I had a lot of weird content that I didn't like in the beginning, too, but after tweaking and using it there's none of that anymore.

**Comment by SebastianRasch** [comment]
One little thing – after switching appearance it shows the settings page instead going back to home. Any chance you could fix it so it would go back to the page it was on before (or just home really would be sufficient I guess)?

**Comment by Andrew-J-Larson** [comment]
> One little thing – after switching appearance it shows the settings page instead going back to home. Any chance you could fix it so it would go back to the page it was on before (or just home really would be sufficient I guess)?

Hmm, I thought I fixed that when I updated it, are you on the latest version?

**Comment by SebastianRasch** [comment]
Yes 1.1.1 should be the latest, right?

I also realised that the first time I reload X after the appearance changed it goes through the settings again even though appearance didn't change, but this time it goes back to home every time reliably.

So appearance changes > I reload X, dark mode gets activated but it gets stuck on the settings. Then I go to "Home" and reload the page again without appearance having changed > it cycles through settings and ends up on "Home" again successfully.

Every other reload after this is just a normal reload without cycling through the settings.

Hope that helps.

**Comment by Andrew-J-Larson** [comment]
> Yes 1.1.1 should be the latest, right?
> 
> I also realised that the first time I reload X after the appearance changed it goes through the settings again even though appearance didn't change, but this time it goes back to home every time reliably.
> 
> So appearance changes > I reload X, dark mode gets activated but it gets stuck on the settings. Then I go to "Home" and reload the page again without appearance having changed > it cycles through settings and ends up on "Home" again successfully.
> 
> Every other reload after this is just a normal reload without cycling through the settings (until appearance changes of course).
> 
> Hope that helps.

I mean, I found a different bug that I fixed, maybe it was related.

Give the 1.1.2 version a test now.

**Comment by Andrew-J-Larson** [comment]
Scratch that, try 1.1.3 @SebastianRasch

**Comment by SebastianRasch** [comment]
Ah I was hoping this would fix everything but unfortunately, it's still the same. It's stuck on Settings > Account.

Interestingly enough, when I deactivate my Adblocker (AdGuard), it doesn't work at all anymore. It's not switching appearance anymore.

**Comment by Andrew-J-Larson** [comment]
> Ah I was hoping this would fix everything but unfortunately, it's still the same. It's stuck on Settings > Account.
> 
> Interestingly enough, when I deactivate my Adblocker (AdGuard), it doesn't work at all anymore. It's not switching appearance anymore.

Are you disabling from the extension, or from the browser?

I suspect AdGuard is probably adding classes to elements, screwing up the query selectors I have.

Try disabling the extension from the extensions page instead, then reload one of the twitter tabs to test, then simulate a theme switch on your device (be it Windows/Mac/Linux etc.)

**Comment by SebastianRasch** [comment]
Haha you're right, I totally forgot. Of course the script is not working anymore when I deactivate AdGuard because it's in the AdGuard userscript manager. 🤦🏻‍♂️
So forget the second part about deactivating my Adblocker. Sorry about that.

**Comment by Andrew-J-Larson** [comment]
> Haha you're right, I totally forgot. Of course the script is not working anymore when I deactivate AdGuard because it's in the AdGuard userscript manager. 🤦🏻‍♂️ So forget the second part about deactivating my Adblocker. Sorry about that.

I did design them from out of Tampermonkey, so it's likely AdGuard adds more classes to elements, messing up selectors I use, or AdGuard's userscript manager doesn't support the same features that Tampermonkey does.

Can you see if the script acts normally in Tampermonkey?

Additionally, when in AdGuard, is there any fine tuning settings per script?

**Comment by SebastianRasch** [comment]
I think it's a Safari problem. I tried in Edge with the script handled by AdGuard and there it works. I also tested it with "[Userscripts](https://apps.apple.com/de/app/userscripts/id1463298887?l=en-GB)" on Safari (because there is no free Tampermonkey extension for Safari/Mac), same problem there, it's stuck on the settings page.

AdGuard has no settings per script apart from edit the code and update/reinstall.

**Comment by Andrew-J-Larson** [comment]
> I think it's a Safari problem. I tried in Edge with the script handled by AdGuard and there it works. I also tested it with "[Userscripts](https://apps.apple.com/de/app/userscripts/id1463298887?l=en-GB)" on Safari (because there is no free Tampermonkey extension for Safari/Mac), same problem there, it's stuck on the settings page.
> 
> AdGuard has no settings per script apart from edit the code and update/reinstall.

Ah yeah, looks like it's a quirk on Safari browsers (Apple making things hard again), but this did enlighten me to find probably a better use case for what I'm trying to achieve anyways.

**Comment by Andrew-J-Larson** [comment]
@SebastianRasch try the 1.1.5 version now in Safari

**Comment by SebastianRasch** [comment]
Yes 1.1.5 works perfectly now in Safari! Thank you so much! 🤗
